language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8
        - COMP=gcc

    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty

    - os: osx
      compiler: gcc
      env:
        - COMPILER=g++-4.8
        - COMP=gcc

branches:
  only:
    - fishnet

before_install:
  - if [ -f /proc/cpuinfo ] ; then cat /proc/cpuinfo; fi

before_script:
  - cd src

script:
  - make clean && make build ARCH=x86-64
