name: Build

on: [push, pull_request]

jobs:
  linux:
    strategy:
      matrix:
        arch: ["x86-64-vnni256", "x86-64-avx512", "x86-64-bmi2", "x86-64-avx2", "x86-64-sse41-popcnt", "x86-64-modern", "x86-64-ssse3", "x86-64-sse3-popcnt", "x86-64", "ppc-64", "armv7"]
        os: ["ubuntu-18.04", "windows-2016", "windows-2019", "macos-11.0", "macos-10.15"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: cd src && make ARCH=${{ matrix.arch }} profile-build
