name: Build

on: [push, pull_request]

jobs:
  freebsd:
    strategy:
      matrix:
        include:
          - arch: x86-64-bmi2
            build: build
          - arch: x86-64-avx2
            build: build
          - arch: x86-64-sse41-popcnt
            build: profile-build
          - arch: x86-64-ssse3
            build: profile-build
          - arch: x86-64-sse3-popcnt
            build: profile-build
          - arch: x86-64
            build: profile-build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vmactions/freebsd-vm@v0.1.2
        with:
          run: pkg install -y gmake curl && cd src && env CXXFLAGS=-DNNUE_EMBEDDING_OFF gmake ARCH=${{ matrix.arch }} COMP=clang ${{ matrix.build }} && strip stockfish
      - run: mv ./src/stockfish stockfish-freebsd-${{ matrix.arch }}
      - uses: actions/upload-artifact@v2
        with:
          name: stockfish
          path: stockfish-*
