name: Build

on: [push, pull_request]

jobs:
  freebsd:
    strategy:
      matrix:
        arch: ["x86-64"]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: vmactions/freebsd-vm@v0.1.2
      with:
        usesh: true
        run: pkg install -y gcc gmake curl && cd src && CXXFLAGS=-DNNUE_EMBEDDING_OFF gmake ARCH=${{ matrix.arch }} profile-build && strip stockfish && ./stockfish compiler
    - run: mv ./src/stockfish stockfish-freebsd-${{ matrix.arch }}
    - uses: actions/upload-artifact@v2
      with:
        name: stockfish
        path: stockfish-*
